title: "प्रragya Lab"
description: "Rooted in Indic Wisdom. Advancing Safe, Multilingual AI."
logo: /assets/img/logo/pragya.png
url: "https://pragyaai.github.io"
baseurl: ""
email: "pragya.ai.research@gmail.com"

markdown: kramdown
theme: al-folio
plugins:
  - jekyll-feed
  - jekyll-seo-tag
