# Site settings
title: "प्रragya Lab"
description: "Rooted in Indic Wisdom. Advancing Safe, Multilingual AI."
url: "https://pragyaai.github.io"
baseurl: ""
email: "pragya.ai.research@gmail.com"

# Build settings
markdown: kramdown
# remote_theme: pages-themes/minimal
remote_theme: pragyaai/al-folio

# Pluginsˇ
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock